---

# Workaround since Ansible modules lock the database similar to `configure exclusive`
- name: "Random Duraion Pause"
  ansible.builtin.pause:
    seconds: "{{ 90 | random(step=6) }}"

- name: "Check If Junos Database Is Open"
  ansible.builtin.junos_config:
    lines:
      - set system license keys
  register: junos_config_db_check
  retries: "{{ task_retries }}"
  delay: "{{ task_retry_delay }}"
  # Not filtering specific database issue or taking into account other errors
  until: (junos_config_db_check['msg'] is not defined)

